### ISSUE TITLE
Usage docs inaccurate

### ISSUE THREAD

**Issue by mslinn** [scala/scala-parallel-collections#64] opened 2019-04-20 19:45 UTC
The **Usage** section of the README for this project says:

> In your code, adding this import:
> 
>     import scala.collection.parallel.CollectionConverters._
> 
> will enable use of the .par method as in earlier Scala versions.
> 

However using that `import` in Scala 2.12.7 results in:

    object CollectionConverters is not a member of package scala.collection.parallel

The equivalent import for Scala 2.12.7 is instead:

    import scala.collection.parallel._

It would be desirable for the old import to continue to work, otherwise older code will break because there is no way to conditionally import based on compiler version.

**Comment by SethTisue** [comment] 2019-04-21 17:07
duplicate of #22?

**Comment by mslinn** [comment] 2019-04-21 19:56
I would say this is not a duplicate because this issue reports an error in documentation that has not previously been mentioned AFAIK.

**Comment by SethTisue** [comment] 2019-04-21 22:10
sorry, but I fail to see how this isn't exactly the same as #22. let's consolidate there: if you think something is missing from #22, please add it as a comment there.

**Closed by SethTisue** 2019-04-21 22:10 UTC

**Comment by SethTisue** [comment] 2019-04-21 22:12
it's also precisely the same, as far as I can tell, as what's already documented in the README at https://github.com/scala/scala-parallel-collections#cross-building-source-compatibility
